Traceback (most recent call last):
  File "/home/njuttu_umass_edu/venvs/torch_env/lib/python3.12/site-packages/huggingface_hub/utils/_http.py", line 409, in hf_raise_for_status
    response.raise_for_status()
  File "/home/njuttu_umass_edu/venvs/torch_env/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/datasets/LawInformedAI/claudette_tos

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/njuttu_umass_edu/685/ZeroShotAnomolyDetection/Zero_shot/run_zeroshot.py", line 18, in <module>
    df = pd.read_parquet(DATASET_PATH)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/njuttu_umass_edu/venvs/torch_env/lib/python3.12/site-packages/pandas/io/parquet.py", line 667, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/home/njuttu_umass_edu/venvs/torch_env/lib/python3.12/site-packages/pandas/io/parquet.py", line 274, in read
    pa_table = self.api.parquet.read_table(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/njuttu_umass_edu/venvs/torch_env/lib/python3.12/site-packages/pyarrow/parquet/core.py", line 1793, in read_table
    dataset = ParquetDataset(
              ^^^^^^^^^^^^^^^
  File "/home/njuttu_umass_edu/venvs/torch_env/lib/python3.12/site-packages/pyarrow/parquet/core.py", line 1348, in __init__
    finfo = filesystem.get_file_info(path_or_paths)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/_fs.pyx", line 590, in pyarrow._fs.FileSystem.get_file_info
  File "pyarrow/error.pxi", line 155, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 89, in pyarrow.lib.check_status
  File "pyarrow/_fs.pyx", line 1498, in pyarrow._fs._cb_get_file_info
  File "/home/njuttu_umass_edu/venvs/torch_env/lib/python3.12/site-packages/pyarrow/fs.py", line 322, in get_file_info
    info = self.fs.info(path)
           ^^^^^^^^^^^^^^^^^^
  File "/home/njuttu_umass_edu/venvs/torch_env/lib/python3.12/site-packages/huggingface_hub/hf_file_system.py", line 683, in info
    resolved_path = self.resolve_path(path, revision=revision)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/njuttu_umass_edu/venvs/torch_env/lib/python3.12/site-packages/huggingface_hub/hf_file_system.py", line 209, in resolve_path
    repo_and_revision_exist, err = self._repo_and_revision_exist(repo_type, repo_id, revision)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/njuttu_umass_edu/venvs/torch_env/lib/python3.12/site-packages/huggingface_hub/hf_file_system.py", line 125, in _repo_and_revision_exist
    self._api.repo_info(
  File "/home/njuttu_umass_edu/venvs/torch_env/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/njuttu_umass_edu/venvs/torch_env/lib/python3.12/site-packages/huggingface_hub/hf_api.py", line 2807, in repo_info
    return method(
           ^^^^^^^
  File "/home/njuttu_umass_edu/venvs/torch_env/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/njuttu_umass_edu/venvs/torch_env/lib/python3.12/site-packages/huggingface_hub/hf_api.py", line 2665, in dataset_info
    hf_raise_for_status(r)
  File "/home/njuttu_umass_edu/venvs/torch_env/lib/python3.12/site-packages/huggingface_hub/utils/_http.py", line 482, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/datasets/LawInformedAI/claudette_tos
